### ISSUE TITLE
Error: Invalid device name '/dev/xvdal'  on starting cluster

### ISSUE THREAD

**Issue by sjobeek** [ContinuumIO/anaconda-ec2#7]
I'm running into this error when trying to start up a basic instance:
ERROR - InvalidBlockDeviceMapping: Invalid device name '/dev/xvdal'

Initialization fails and I'm unable to get the cluster running.

I'm using 32-bit anaconda on a windows machine, with all starcluster dependencies freshly installed with pip. 

This is the only hint of a similar error message I could find on a Google search:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/684875

While other AMI images do work properly, it seems that the Anaconda AMIs break on install even without the fancy scripts included here.  Perhaps something changed and they need to be updated?

Error log:

```
C:\Users\sjoberge>starcluster start -s 1 ancluster
StarCluster - (http://star.mit.edu/cluster) (v. 0.94)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Using default cluster template: smallcluster
>>> Validating cluster template settings...
>>> Cluster template settings are valid
>>> Starting cluster...
>>> Launching a 1-node cluster...
>>> Creating security group @sc-ancluster...
>>> Opening tcp port range 8989-8989 for CIDR 0.0.0.0/0
!!! ERROR - InvalidBlockDeviceMapping: Invalid device name '/dev/xvdal'
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\starcluster\cli.py", line 274, in main
    sc.execute(args)
  File "C:\Anaconda\lib\site-packages\starcluster\commands\start.py", line 215,
in execute
    validate_running=validate_running)
  File "C:\Anaconda\lib\site-packages\starcluster\cluster.py", line 1471, in sta
rt
    return self._start(create=create, create_only=create_only)
  File "<string>", line 2, in _start
  File "C:\Anaconda\lib\site-packages\starcluster\utils.py", line 111, in wrap_f

    res = func(*arg, **kargs)
  File "C:\Anaconda\lib\site-packages\starcluster\cluster.py", line 1486, in _st
art
    self.create_cluster()
  File "C:\Anaconda\lib\site-packages\starcluster\cluster.py", line 1012, in cre
ate_cluster
    self._create_flat_rate_cluster()
  File "C:\Anaconda\lib\site-packages\starcluster\cluster.py", line 1036, in _cr
eate_flat_rate_cluster
    force_flat=True)[0]
  File "C:\Anaconda\lib\site-packages\starcluster\cluster.py", line 844, in crea
te_nodes
    resvs.append(self.ec2.request_instances(image_id, **kwargs))
  File "C:\Anaconda\lib\site-packages\starcluster\awsutils.py", line 443, in req
uest_instances
    block_device_map=block_device_map)
  File "C:\Anaconda\lib\site-packages\starcluster\awsutils.py", line 471, in run
_instances
    block_device_map=block_device_map)
  File "C:\Anaconda\lib\site-packages\boto\ec2\connection.py", line 725, in run_
instances
    verb='POST')
  File "C:\Anaconda\lib\site-packages\boto\connection.py", line 1096, in get_obj
ect
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidBlockDeviceMapping</Code><Message>Invalid
device name '/dev/xvdal'</Message></Error></Errors><RequestID>8e33446d-de4f-4e9e
-bcfa-2bad7035630b</RequestID></Response>
```

**Comment by jtriley** [comment]
@sjobeek This is a regression in StarCluster with S3-backed AMIs. This is not an issue with EBS AMIs. I'm working on a fix now.

**Comment by jtriley** [comment]
OK, that last commit to StarCluster should fix this bug. I'm planning on releasing StarCluster 0.94.1 soon which will include this fix.

**Comment by jtriley** [comment]
@quasiben This has been fixed since 0.94.1 and 0.94.3 is out now. Should be safe to close this.
